### ISSUE TITLE
Website issues and suggestions

### ISSUE THREAD

**Issue by kozaxinan** [JetBrains/JetBrainsMono#340]
- Website download button downloads 2.201. Not the latest released version. (Brew doesnt download the latest version as well)
- Website still shows Apache 2.0 license instead of OFL-1.1 License.
- Website installation could include brew.

**Comment by kozaxinan** [comment]
Brew is updated.

**Comment by philippnurullin** [comment]
Hi @kozaxinan 

- True. Regarding Brew, i have no idea how JetBrians Mono getting there.
- We corrected the License, soon will be on production.
- Because we don't manage Brew we don't include it on the Landing Page.

**Comment by kozaxinan** [comment]
- Website still shows and downloads old version.
- Great
- Brew cask-fonts is an open source repo. Jetbrains mono releases could also update that cask-font as well. Pr about last release https://github.com/Homebrew/homebrew-cask-fonts/pull/2506

**Comment by philippnurullin** [comment]
The website is updated to the latest version. It will be faster in the future. The process is automated.
We will think on adding the Brew link to the page.

**Comment by m-vlad** [comment]
The big button in the hero is pointing to version 1.0.3

**Comment by philippnurullin** [comment]
@m-vlad Hi, we cannot reproduce the problem.
Please add more info. On what loading stage the URL is not correct? Please include the screenshots if possible, this always makes things clearer.

**Comment by philippnurullin** [comment]
@m-vlad What OS and browser you using?

**Comment by m-vlad** [comment]
@philippnurullin Vivaldi, Windows 11
Just on the homepage and just for an instant.
Here's a video showing me refresh the page and the link updating on the fly. Anyway it'd be much better
https://user-images.githubusercontent.com/22298459/155439139-13c4e3a4-db5d-481b-95ac-083727ec692d.mp4

Also I'm surprised you guys don't just keep the same zip name between releases, because then you could use something like https://github.com/JetBrains/JetBrainsMono/releases/latest/download/JetBrainsMono.zip to link to the newest release at all times.
